import {
  ALL_PERMISSIONS,
  PERMISSIONS,
  Permission,
} from '../permissions/permissions.constants';

export const SYSTEM_ROLE_NAMES = {
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  BRANCH_ADMIN: 'BRANCH_ADMIN',
  DEPARTMENT_MANAGER: 'DEPARTMENT_MANAGER',
  STAFF: 'STAFF',
  PRINCIPAL: 'PRINCIPAL',
  TEACHER: 'TEACHER',
  ACCOUNTANT: 'ACCOUNTANT',
  GATE_OFFICER: 'GATE_OFFICER',
} as const;

interface SystemRoleDef {
  name: string;
  description: string;
  permissions: readonly Permission[];
}

/**
 * Seed definitions for the system roles created per tenant on registration.
 * Admin-assigned scope (RoleAssignment.branchId) decides whether the role
 * applies company-wide or within a specific branch.
 */
export const SYSTEM_ROLE_DEFS: Record<
  keyof typeof SYSTEM_ROLE_NAMES,
  SystemRoleDef
> = {
  COMPANY_ADMIN: {
    name: SYSTEM_ROLE_NAMES.COMPANY_ADMIN,
    description:
      'Root administrator of the company. Full access to all company settings and data.',
    permissions: ALL_PERMISSIONS,
  },
  BRANCH_ADMIN: {
    name: SYSTEM_ROLE_NAMES.BRANCH_ADMIN,
    description:
      'Administrator of a single branch. Manages staff, content, workflows and attendance within the branch.',
    permissions: [
      PERMISSIONS.BRANCH_VIEW,
      PERMISSIONS.BRANCH_UPDATE,
      PERMISSIONS.DEPARTMENT_VIEW,
      PERMISSIONS.DEPARTMENT_CREATE,
      PERMISSIONS.DEPARTMENT_UPDATE,
      PERMISSIONS.DEPARTMENT_DELETE,
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.GROUP_CREATE,
      PERMISSIONS.GROUP_UPDATE,
      PERMISSIONS.GROUP_DELETE,
      PERMISSIONS.STAFF_VIEW,
      PERMISSIONS.STAFF_CREATE,
      PERMISSIONS.STAFF_UPDATE,
      PERMISSIONS.STAFF_DELETE,
      PERMISSIONS.STAFF_ASSIGN_ROLE,
      PERMISSIONS.ROLE_VIEW,
      PERMISSIONS.ROLE_CREATE,
      PERMISSIONS.ROLE_UPDATE,
      PERMISSIONS.ROLE_DELETE,
      PERMISSIONS.ROLE_ASSIGN,
      PERMISSIONS.ATTENDANCE_VIEW,
      PERMISSIONS.ATTENDANCE_MANAGE,
      PERMISSIONS.SCHEDULE_MANAGE,
      PERMISSIONS.DOCUMENT_VIEW,
      PERMISSIONS.DOCUMENT_CREATE,
      PERMISSIONS.DOCUMENT_UPDATE,
      PERMISSIONS.DOCUMENT_DELETE,
      PERMISSIONS.INVENTORY_VIEW,
      PERMISSIONS.INVENTORY_MANAGE,
      PERMISSIONS.MEMO_VIEW,
      PERMISSIONS.MEMO_CREATE,
      PERMISSIONS.MEMO_MANAGE,
      PERMISSIONS.FORM_VIEW,
      PERMISSIONS.FORM_CREATE,
      PERMISSIONS.FORM_MANAGE,
      PERMISSIONS.FORM_SUBMIT,
      PERMISSIONS.REPORT_VIEW,
      PERMISSIONS.REPORT_SUBMIT,
      PERMISSIONS.REPORT_MANAGE,
      PERMISSIONS.WORKFLOW_VIEW,
      PERMISSIONS.WORKFLOW_CREATE,
      PERMISSIONS.WORKFLOW_SUBMIT,
      PERMISSIONS.WORKFLOW_APPROVE,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
      PERMISSIONS.AUDIT_VIEW,
    ],
  },
  DEPARTMENT_MANAGER: {
    name: SYSTEM_ROLE_NAMES.DEPARTMENT_MANAGER,
    description: 'Manages staff and day-to-day operations within a department.',
    permissions: [
      PERMISSIONS.DEPARTMENT_VIEW,
      PERMISSIONS.GROUP_VIEW,
      PERMISSIONS.STAFF_VIEW,
      PERMISSIONS.STAFF_CREATE,
      PERMISSIONS.STAFF_UPDATE,
      PERMISSIONS.ATTENDANCE_VIEW,
      PERMISSIONS.DOCUMENT_VIEW,
      PERMISSIONS.DOCUMENT_CREATE,
      PERMISSIONS.INVENTORY_VIEW,
      PERMISSIONS.MEMO_VIEW,
      PERMISSIONS.MEMO_CREATE,
      PERMISSIONS.FORM_VIEW,
      PERMISSIONS.FORM_SUBMIT,
      PERMISSIONS.REPORT_VIEW,
      PERMISSIONS.REPORT_SUBMIT,
      PERMISSIONS.REPORT_MANAGE,
      PERMISSIONS.WORKFLOW_VIEW,
      PERMISSIONS.WORKFLOW_SUBMIT,
      PERMISSIONS.WORKFLOW_APPROVE,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
    ],
  },
  STAFF: {
    name: SYSTEM_ROLE_NAMES.STAFF,
    description:
      'Regular staff member. Can clock in/out, view assigned content and submit workflows.',
    permissions: [
      PERMISSIONS.ATTENDANCE_CLOCK_IN,
      PERMISSIONS.ATTENDANCE_CLOCK_OUT,
      PERMISSIONS.ATTENDANCE_VIEW,
      PERMISSIONS.DOCUMENT_VIEW,
      PERMISSIONS.MEMO_VIEW,
      PERMISSIONS.FORM_SUBMIT,
      PERMISSIONS.WORKFLOW_SUBMIT,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
    ],
  },
  PRINCIPAL: {
    name: SYSTEM_ROLE_NAMES.PRINCIPAL,
    description:
      'School principal / head of school with full administrative and academic oversight.',
    permissions: [
      PERMISSIONS.TENANT_VIEW,
      PERMISSIONS.TENANT_MANAGE,
      PERMISSIONS.SCHOOL_VIEW,
      PERMISSIONS.SCHOOL_MANAGE,
      PERMISSIONS.STUDENT_VIEW,
      PERMISSIONS.STUDENT_MANAGE,
      PERMISSIONS.ACADEMIC_VIEW,
      PERMISSIONS.ACADEMIC_MANAGE,
      PERMISSIONS.SCHOOL_FEE_VIEW,
      PERMISSIONS.SCHOOL_FEE_MANAGE,
      PERMISSIONS.SCHOOL_ATTENDANCE_VIEW,
      PERMISSIONS.SCHOOL_ATTENDANCE_MANAGE,
      PERMISSIONS.STAFF_VIEW,
      PERMISSIONS.STAFF_CREATE,
      PERMISSIONS.STAFF_UPDATE,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
      PERMISSIONS.DOCUMENT_VIEW,
      PERMISSIONS.DOCUMENT_CREATE,
      PERMISSIONS.MEMO_VIEW,
      PERMISSIONS.MEMO_CREATE,
      PERMISSIONS.REPORT_VIEW,
    ],
  },
  TEACHER: {
    name: SYSTEM_ROLE_NAMES.TEACHER,
    description:
      'Classroom and subject instructor managing students, attendance, continuous assessment, and scores.',
    permissions: [
      PERMISSIONS.SCHOOL_VIEW,
      PERMISSIONS.STUDENT_VIEW,
      PERMISSIONS.ACADEMIC_VIEW,
      PERMISSIONS.ACADEMIC_MANAGE,
      PERMISSIONS.SCHOOL_ATTENDANCE_VIEW,
      PERMISSIONS.SCHOOL_ATTENDANCE_MANAGE,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
      PERMISSIONS.DOCUMENT_VIEW,
      PERMISSIONS.DOCUMENT_CREATE,
      PERMISSIONS.MEMO_VIEW,
    ],
  },
  ACCOUNTANT: {
    name: SYSTEM_ROLE_NAMES.ACCOUNTANT,
    description:
      'School bursar/accountant managing fee schedules, student billing, payments, and receipts.',
    permissions: [
      PERMISSIONS.SCHOOL_VIEW,
      PERMISSIONS.STUDENT_VIEW,
      PERMISSIONS.SCHOOL_FEE_VIEW,
      PERMISSIONS.SCHOOL_FEE_MANAGE,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
      PERMISSIONS.DOCUMENT_VIEW,
      PERMISSIONS.REPORT_VIEW,
    ],
  },
  GATE_OFFICER: {
    name: SYSTEM_ROLE_NAMES.GATE_OFFICER,
    description:
      'Security and gate attendance operator scanning student ID cards, RFID, and registering visitor/student entry.',
    permissions: [
      PERMISSIONS.SCHOOL_VIEW,
      PERMISSIONS.STUDENT_VIEW,
      PERMISSIONS.SCHOOL_ATTENDANCE_VIEW,
      PERMISSIONS.SCHOOL_ATTENDANCE_MANAGE,
      PERMISSIONS.CHAT_CREATE,
      PERMISSIONS.CHAT_VIEW,
    ],
  },
};
